version: 2

project_name: muxie

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/muxie
    binary: muxie
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      - darwin
    goarch:
      - amd64
      # - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  name_template: "{{.Tag}}"
  draft: false
  prerelease: auto
  extra_files:
    - glob: LICENSE
    - glob: README.md

brews:
  - name: muxie
    repository:
      owner: phanorcoll
      name: homebrew-muxie
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: phanor coll
      email: phanorcoll@gmail.com
    homepage: "https://github.com/phanorcoll/muxie"
    description: "A fast and flexible tmux session manager for organizing, launching, and automating tmux workspaces with ease."
    license: "MIT"
